/**
 * Consumer hardware funnel: phones, PCs, wearables, home entertainment, gaming,
 * personal cameras/drones, and enthusiast PC parts—not datacenter silicon, lab
 * gear, or DIY maker benches.
 */

const PROMO_OR_EVENT_SPAM =
  /techcrunch\s+disrupt|disrupt\s+20\d{2}.*\b(ticket|register|save\s+(?:nearly|up\s+to)|\$\d+)/i;

/** Cloud, enterprise silicon, industrial automation, or hobbyist bench projects. */
const ENTERPRISE_OR_MAKER_EXCLUDE =
  /\b(?:trainium|inferentia|cloud\s+tpu|tpu\s+v\d+|nvidia\s+h100|nvidia\s+h200|\bepyc\b|\bxeon\b|\bh100\b|\bh200\b|\bb200\b|exascale|supercomputer|hyperscaler|data\s+center|data\s*centr|datacenter|oscilloscope|logic\s+analyzer|\bfpga\b|verilog|vhdl|arduino|raspberry\s*pi|esp32|esp8266|pick-and-place|reflow\s+oven|warehouse\s+robot|industrial\s+robot|factory\s+automation|plc\s+controller)\b/i;

/**
 * Things people buy for themselves or the home—or mainstream retail PC upgrades.
 */
const CONSUMER_HARDWARE_SIGNAL = new RegExp(
  [
    String.raw`smartphone`,
    String.raw`smartphones`,
    String.raw`mobile\s+phone`,
    String.raw`iphone`,
    String.raw`ipad`,
    String.raw`macbook`,
    String.raw`imac`,
    String.raw`mac\s*mini`,
    String.raw`tablet`,
    String.raw`laptop`,
    String.raw`chromebook`,
    String.raw`2[\s-]in[\s-]1`,
    String.raw`convertible\s+laptop`,
    String.raw`ultrabook`,
    String.raw`foldable\s+(?:phone|tablet)`,
    String.raw`\bpixel\b`,
    String.raw`galaxy\s+(?:s|z|a|fold|flip|tab|watch|bud)`,
    String.raw`oneplus`,
    String.raw`nothing\s+phone`,
    String.raw`xiaomi`,
    String.raw`oppo`,
    String.raw`vivo`,
    String.raw`smartwatch`,
    String.raw`apple\s+watch`,
    String.raw`fitness\s+(?:tracker|band)`,
    String.raw`wearable`,
    String.raw`oura`,
    String.raw`whoop`,
    String.raw`earbuds`,
    String.raw`airpods`,
    String.raw`headphones`,
    String.raw`headset`,
    String.raw`soundbar`,
    String.raw`(?:smart\s*)?(?:ring|glasses)`,
    String.raw`ray[\s-]ban`,
    String.raw`meta\s+quest`,
    String.raw`\bpsvr\b`,
    String.raw`vision\s+pro`,
    String.raw`\bvr\b`,
    String.raw`mixed\s+reality`,
    String.raw`steam\s+deck`,
    String.raw`rog\s+ally`,
    String.raw`legion\s+go`,
    String.raw`gaming\s+handheld`,
    String.raw`handheld\s+console`,
    String.raw`nintendo\s+switch`,
    String.raw`\bswitch\s+2\b`,
    String.raw`playstation`,
    String.raw`\bps5\b`,
    String.raw`\bps6\b`,
    String.raw`\bxbox\b`,
    String.raw`series\s+[sx]\b`,
    String.raw`console`,
    String.raw`smart\s*tv`,
    String.raw`oled\s*tv`,
    String.raw`qled`,
    String.raw`google\s*tv`,
    String.raw`chromecast`,
    String.raw`fire\s*tv`,
    String.raw`roku`,
    String.raw`apple\s*tv`,
    String.raw`streaming\s*stick`,
    String.raw`homepod`,
    String.raw`echo\s*(?:dot|show|studio)?`,
    String.raw`\balexa\b`,
    String.raw`\bnest\b`,
    String.raw`ring\s+(?:doorbell|camera)`,
    String.raw`smart\s+(?:lock|thermostat|plug|bulb|display)`,
    String.raw`roomba`,
    String.raw`robot\s+vacuum`,
    String.raw`mirrorless`,
    String.raw`dslr`,
    String.raw`action\s+cam`,
    String.raw`gopro`,
    String.raw`insta360`,
    String.raw`\bdji\b`,
    String.raw`drone`,
    String.raw`quadcopter`,
    String.raw`gimbal`,
    String.raw`electric\s+(?:car|suv|truck|vehicle)`,
    String.raw`\bev\b`,
    String.raw`\btesla\b`,
    String.raw`cybertruck`,
    String.raw`rivian`,
    String.raw`graphics\s+card`,
    String.raw`video\s+card`,
    String.raw`geforce`,
    String.raw`radeon`,
    String.raw`\brtx\b`,
    String.raw`\brx\s*7`,
    String.raw`snapdragon`,
    String.raw`tensor\b`,
    String.raw`apple\s*silicon`,
    String.raw`m\d+\s+chip`,
    String.raw`a\d+\s+(?:bionic|chip)`,
    String.raw`phone\s+chip`,
    String.raw`mobile\s+chip`,
    String.raw`\bgpu\b`,
    String.raw`\bcpu\b`,
    String.raw`gaming\s+(?:pc|laptop|monitor|keyboard|mouse)`,
    String.raw`monitor`,
    String.raw`ultrawide`,
    String.raw`keyboard`,
    String.raw`mechanical\s+keyboard`,
    String.raw`mouse\b`,
    String.raw`trackball`,
    String.raw`webcam`,
    String.raw`motherboard`,
    String.raw`\bssd\b`,
    String.raw`nvme`,
    String.raw`\bram\b`,
    String.raw`\bddr4\b`,
    String.raw`\bddr5\b`,
    String.raw`memory\s+module`,
    String.raw`\bpsu\b`,
    String.raw`power\s+supply`,
    String.raw`pc\s+case`,
    String.raw`cpu\s+cooler`,
    String.raw`aio\s+cooler`,
    String.raw`overclock`,
    String.raw`benchmark`,
    String.raw`teardown`,
    String.raw`gadget`,
    String.raw`consumer\s+electronics`,
    String.raw`robot`,
    String.raw`humanoid`,
    String.raw`\bces\b`,
    String.raw`\bmwc\b`,
    String.raw`computex`,
    String.raw`\bifa\b`,
  ].join("|"),
  "i"
);

export function shouldIncludeHardwareNewsItem(
  title: string,
  summary: string | null
): boolean {
  const corpus = `${title} ${summary ?? ""}`;
  if (PROMO_OR_EVENT_SPAM.test(corpus)) return false;
  if (ENTERPRISE_OR_MAKER_EXCLUDE.test(corpus)) return false;
  return CONSUMER_HARDWARE_SIGNAL.test(corpus);
}
